"""Corrected EK1D copper tutorial, version 2.1.0.

theta dc_i/dt = -div(J_i) + theta R_i, with pore-water c in mol/m3,
J_i = -Dstar_i grad(c_i) + z_i F/(RT) Dstar_i E c_i, and
Dstar_i = theta D0_i/tau. All fluxes are per bulk cross-sectional area.

The saturated, hydraulically closed column has q_total=0. Its induced
hydraulic counterflow cancels EOF (q_h=-k_eo E); pressure magnitude is not
calculated because hydraulic permeability is not specified. Cu, Na and NO3
cannot cross the endpoints. Ideal Faradaic H/OH injection uses the SAME
uniform ionic current as the interior fluxes. Endpoint solution potentials
are 20 and 0 V; electrode overpotentials, gas, heat and activity corrections
are omitted. This is an illustrative redistribution model, not a Cu recovery
experiment or an independently validated remediation prediction.

Current continuity is solved exactly for the piecewise-linear upwind face
law, including reversed local fields and diffusion current. Transport is
explicit conservative finite volume with simultaneous water, sorption and
reversible precipitation equilibrium. SSPRK2 reconstructs equilibrium after
each forward transport stage and the final component mixture. The combined
outgoing-coefficient CFL includes theta. No concentrations are
clipped and no ion is adjusted to repair charge during time integration.

Article case: python reproduce.py --case N400_cfl01 --output rerun_selected --backend native
Run commands, companion modules and reference-data instructions are in README.md.
The article figures are generated by plot_article_figures.py; save() also writes
separate per-run diagnostic plots.
"""
from dataclasses import dataclass, asdict
from pathlib import Path
import argparse
import hashlib
import json
import platform
import time
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from chemistry import react

VERSION = "2.1.0"
F = 96485.0
Rg = 8.314
T = 298.15
FRT = F/(Rg*T)


@dataclass
class P:
    L: float = 0.10
    N: int = 100
    theta: float = 0.45
    tau: float = 1.6
    V: float = 20.0
    keo: float = 1.2e-9
    Kw: float = 1e-14
    Ksp: float = 2.2e-20
    pH50: float = 5.5
    nedge: float = 2.0
    pH0: float = 5.0
    Cu_tot0: float = 5.0
    Na0: float = 10.0
    dt: float = 15.0
    cfl: float = 0.4
    tend: float = 129600.0
    output_dt: float = 600.0
    spatial_order: int = 1
    algebraic_chemistry: bool = True
    time_order: int = 1
    names = ("H", "OH", "Cu", "Na", "NO3")
    z = np.array([1., -1., 2., 1., -1.])
    D0 = np.array([9.31e-9, 5.27e-9, .714e-9, 1.33e-9, 1.90e-9])


def grid(p):
    dx = p.L/p.N
    return dx, (np.arange(p.N)+.5)*dx, p.D0*p.theta/p.tau


def initialise(p):
    c = np.zeros((5, p.N))
    c[0] = 1000*10**(-p.pH0)
    c[1] = 1000*p.Kw/10**(-p.pH0)
    ratio = 10**(p.nedge*(p.pH0-p.pH50))
    c[2] = p.Cu_tot0/(1+ratio)
    cs = p.Cu_tot0-c[2]
    cp = np.zeros(p.N)
    c[3] = p.Na0
    c[4] = c[0]-c[1]+2*c[2]+c[3]
    if np.min(c) < 0:
        raise ValueError("Specified initial state needs negative nitrate.")
    # Ensures phase equilibrium for non-default initial conditions as well.
    c, cs, cp, _ = react(c, cs, cp, p)
    return c, cs, cp


def migration_face_states(c, spatial_order):
    """Cell-donor or positive monotone MC reconstruction for migration."""
    cL, cR = c[:, :-1], c[:, 1:]
    if spatial_order == 1:
        return cL, cR
    if spatial_order != 2:
        raise ValueError('spatial_order must be 1 or 2.')
    slope = np.zeros_like(c)
    dl, dr = c[:, 1:-1]-c[:, :-2], c[:, 2:]-c[:, 1:-1]
    slope[:, 1:-1] = np.where(dl*dr > 0, np.sign(dl)*np.minimum(
        np.minimum(2*np.abs(dl), 2*np.abs(dr)), .5*np.abs(dl+dr)), 0.)
    migration_L = cL+.5*slope[:, :-1]
    migration_R = cR-.5*slope[:, 1:]
    if np.min(migration_L) < 0 or np.min(migration_R) < 0:
        raise FloatingPointError("Negative reconstructed migration state.")
    return migration_L, migration_R


def electrical(c, dx, D, p):
    """Exact sign-consistent 1D current closure, without conductivity floors.

    At an interior face, j = d_f + sigma_+(or -) E_f. Inverting this
    relation gives a monotone piecewise-linear voltage function of j.
    Sorting the breakpoints d_f allows all candidate intervals to be
    evaluated in one vectorized operation. Half-cell endpoint resistances
    use adjacent-cell conductivity and zero boundary diffusion current.
    """
    if not np.isfinite(c).all() or np.min(c) < 0:
        raise FloatingPointError("Non-finite or negative aqueous concentration.")
    z = p.z[:, None]
    cL, cR = c[:, :-1], c[:, 1:]
    migration_L, migration_R = migration_face_states(c, p.spatial_order)
    factor = F*FRT*p.z**2*D
    sigma = np.sum(factor[:, None]*c, axis=0)
    sp = np.sum(factor[:, None]*np.where(z > 0, migration_L, migration_R), axis=0)
    sm = np.sum(factor[:, None]*np.where(z > 0, migration_R, migration_L), axis=0)
    if min(np.min(sigma), np.min(sp), np.min(sm)) <= 0:
        raise FloatingPointError("Nonpositive physical conductivity.")
    diff = -F*np.sum(z*D[:, None]*(cR-cL)/dx, axis=0)
    order = np.argsort(diff)
    ds = diff[order]
    rm, rp = dx/sm[order], dx/sp[order]
    rbound = dx*.5*(1/sigma[0]+1/sigma[-1])
    dr = rp-rm
    rr = np.r_[rbound+np.sum(rm), rbound+np.sum(rm)+np.cumsum(dr)]
    rd = np.r_[np.dot(rm, ds), np.dot(rm, ds)+np.cumsum(dr*ds)]
    candidates = (p.V+rd)/rr
    lo, hi = np.r_[-np.inf, ds], np.r_[ds, np.inf]
    idx = np.flatnonzero((candidates >= lo) & (candidates <= hi))
    if len(idx):
        j = float(candidates[idx[0]])
    else:
        # Exactly zero-field breakpoints can fall outside both adjacent
        # intervals through roundoff. Solve the original monotone voltage
        # law in that rare case; do not perturb concentrations/conductivity.
        def residual(jj):
            return jj*rbound+np.sum(dx*(jj-diff)/np.where(jj >= diff, sp, sm))-p.V
        extent = max(abs(p.V)/rbound, 1.)
        lower, upper = min(0., float(np.min(diff)))-extent, max(0., float(np.max(diff)))+extent
        while residual(lower) > 0:
            lower -= extent
            extent *= 2
        while residual(upper) < 0:
            upper += extent
            extent *= 2
        for _ in range(100):
            middle = .5*lower+.5*upper
            if middle == lower or middle == upper:
                break
            if residual(middle) < 0:
                lower = middle
            else:
                upper = middle
        j = min((lower, upper), key=lambda jj: abs(residual(jj)))
    sf = np.where(j >= diff, sp, sm)
    # Re-sum the selected branch to avoid cancellation in the prefix sums.
    resistance = dx/sf
    j = float((p.V+np.dot(resistance, diff))/(rbound+np.sum(resistance)))
    sf = np.where(j >= diff, sp, sm)
    E = (j-diff)/sf
    voltage = j*rbound+np.sum(E)*dx
    phi = np.r_[p.V-j*dx/(2*sigma[0]),
                p.V-j*dx/(2*sigma[0])-np.cumsum(E)*dx]
    w = p.z[:, None]*FRT*D[:, None]*E
    donor_L = np.divide(migration_L, cL, out=np.ones_like(cL), where=cL > 0)
    donor_R = np.divide(migration_R, cR, out=np.ones_like(cR), where=cR > 0)
    left = D[:, None]/dx+np.maximum(w, 0)*donor_L
    right = D[:, None]/dx+np.maximum(-w, 0)*donor_R
    J = left*cL-right*cR
    actual_j = F*np.sum(z*J, axis=0)
    residual = float(np.max(np.abs(actual_j-j)))
    return dict(j=j, E=E, phi=phi, sigma=sigma, flux=J,
                left=left, right=right, current_residual=residual,
                voltage_residual=float(abs(voltage-p.V)))


def boundary_flux(j, p):
    """Oriented +x flux at x=0 and x=L, ideal unit Faradaic efficiency."""
    bc = np.zeros((5, 2))
    if j >= 0:
        bc[0, 0] = j/F
        bc[1, 1] = -j/F
    else:
        bc[1, 0] = -j/F
        bc[0, 1] = j/F
    return bc


def transport_step(c, el, dt_limit, dx, p):
    out = np.zeros_like(c)
    out[:, :-1] += el["left"]
    out[:, 1:] += el["right"]
    dt = min(dt_limit, p.cfl*p.theta*dx/float(np.max(out)))
    J = np.empty((5, p.N+1))
    J[:, 1:-1] = el["flux"]
    J[:, (0, -1)] = boundary_flux(el["j"], p)
    new = c + dt/(p.theta*dx)*(J[:, :-1]-J[:, 1:])
    if np.min(new) < 0 or not np.isfinite(new).all():
        raise FloatingPointError("Transport positivity failed; step not accepted.")
    return new, dt, J


def inventories(c, cs, cp, dx, p):
    scale = p.theta*dx
    return np.array([np.sum(c[2]+cs+cp), np.sum(c[3]), np.sum(c[4])])*scale


def chemistry_residuals(c, cs, cp, p):
    h, oh, cu = c[:3]/1000
    ratio = (10**(-p.pH50)/h)**p.nedge
    total = c[2]+cs+cp
    scale = np.maximum(total, 1e-15)
    ip = cu*oh**2/p.Ksp
    present = cp > 1e-12
    return dict(water=float(np.max(np.abs(h*oh/p.Kw-1))),
                sorption=float(np.max(np.abs(cs-ratio*c[2])/scale)),
                precipitation=float(max(np.max(np.maximum(ip-1, 0)),
                    np.max(np.abs(ip[present]-1)) if present.any() else 0)))


def coupled_step(c, cs, cp, dx, D, limit, p):
    """Euler or SSPRK2 on conserved components, with equilibrium projection.

    Both stages use freshly evaluated electrical and positivity constraints.
    A failed second-stage CFL trial is discarded in its entirety. The final
    convex mixture includes immobile inventories before equilibrium.
    """
    e0=electrical(c,dx,D,p)
    c1raw,dt,_=transport_step(c,e0,limit,dx,p)
    rejected=0
    while True:
        c1,s1,b1,_=react(c1raw,cs,cp,p)
        if p.time_order == 1:
            new,ns,nb=c1,s1,b1
            e1=e0
            minimum=min(float(c1raw.min()),float(c1.min()))
            break
        if p.time_order != 2:
            raise ValueError('time_order must be 1 or 2.')
        e1=electrical(c1,dx,D,p)
        c2raw,dt2,_=transport_step(c1,e1,dt,dx,p)
        if dt2 < dt*(1-1e-12):
            rejected+=1
            if rejected>30:
                raise RuntimeError('SSPRK2 could not satisfy the second-stage positivity bound.')
            c1raw,dt,_=transport_step(c,e0,.99*dt2,dx,p)
            continue
        mixed=.5*(c+c2raw)
        new,ns,nb,_=react(mixed,.5*(cs+s1),.5*(cp+b1),p)
        minimum=min(float(c1raw.min()),float(c1.min()),float(c2raw.min()),float(new.min()))
        break
    chem1=chemistry_residuals(c1,s1,b1,p)
    chem2=chemistry_residuals(new,ns,nb,p)
    q1=np.sum(p.z[:,None]*c1,axis=0)
    q2=np.sum(p.z[:,None]*new,axis=0)
    den1=np.sum(np.abs(p.z[:,None]*c1),axis=0)
    den2=np.sum(np.abs(p.z[:,None]*new),axis=0)
    stats=dict(minimum_aqueous_mol_m3=minimum,rejected_steps=rejected,
        mean_signed_current_A_m2=.5*(e0['j']+e1['j']),
        mean_absolute_current_A_m2=.5*(abs(e0['j'])+abs(e1['j'])),
        current_stage0_A_m2=e0['j'],current_stage1_A_m2=e1['j'],
        max_current_residual_A_m2=max(e0['current_residual'],e1['current_residual']),
        max_voltage_residual_V=max(e0['voltage_residual'],e1['voltage_residual']),
        max_charge_mol_m3=max(float(abs(q1).max()),float(abs(q2).max())),
        max_normalized_charge=max(float(np.max(abs(q1)/den1)),float(np.max(abs(q2)/den2))),
        max_chemistry_residuals={k:max(chem1[k],chem2[k]) for k in chem1})
    return new,ns,nb,dt,stats


def run(p, verbose=True, backend='python'):
    validate_parameters(p)
    tic = time.perf_counter()
    source_root = Path(__file__).resolve().parent
    source_hashes = {name: hashlib.sha256((source_root/name).read_bytes()).hexdigest()
        for name in ('EK1D_tutorial.py', 'chemistry.py', 'native_backend.py', 'native_kernel.cpp')
        if (source_root/name).exists()}
    dx, x, D = grid(p)
    c, cs, cp = initialise(p)
    if backend not in ('python', 'native'):
        raise ValueError("Backend must be 'python' or 'native'.")
    if backend == 'native':
        from native_backend import advance
    initial = inventories(c, cs, cp, dx, p)
    t = 0.0
    steps = 0
    rejected_steps = 0
    min_dt, max_dt = np.inf, 0.
    minimum = float(np.min(c))
    max_charge, max_charge_fraction = 0., 0.
    max_current_residual, max_voltage_residual = 0., 0.
    max_inv_error = np.zeros(3)
    max_chem = dict(water=0., sorption=0., precipitation=0.)
    native_chemistry_stats = dict(max_iterations=0, algebraic_calls=0, generic_calls=0,
        max_local_charge_residual_mol_m3=0., max_local_Cu_residual_mol_m3=0.)
    faradaic_moles = 0.
    signed_charge = 0.
    all_times = sorted(set([0., p.tend]+list(np.arange(p.output_dt, p.tend, p.output_dt))+
                           [h*3600 for h in (6, 24, 36) if h*3600 <= p.tend]))
    snaps, times, currents, series = {}, [], [], []
    phase_series, charge_series, faradaic_series, current_envelopes = [], [], [], []
    chunk_current_min, chunk_current_max = np.inf, -np.inf

    def record():
        el = electrical(c, dx, D, p)
        times.append(t)
        currents.append(el['j'])
        phase_series.append(np.array([c[2].sum(), cs.sum(), cp.sum()])*p.theta*dx)
        charge_series.append(signed_charge)
        faradaic_series.append(faradaic_moles)
        current_envelopes.append([el['j'],el['j']] if t == 0 else
                                 [chunk_current_min,chunk_current_max])
        series.append([*inventories(c, cs, cp, dx, p),
                       np.max(np.abs(np.sum(p.z[:, None]*c, axis=0)))])
        if t == 0 or t == p.tend or t in (21600., 86400., 129600.):
            snaps[t] = dict(c=c.copy(), Cu_s=cs.copy(), Cu_ppt=cp.copy(),
                            pH=-np.log10(c[0]/1000), phi=el['phi'],
                            E=el['E'], j=np.array(el['j']))
        if verbose:
            print(f"t={t/3600:.3f} h j={el['j']:.8g} A/m2 steps={steps}", flush=True)

    record()
    for target in all_times[1:]:
        chunk_current_min, chunk_current_max = np.inf, -np.inf
        if backend == 'native':
            c, cs, cp, m = advance(c, cs, cp, p, target-t, initial)
            steps += m['accepted_steps']
            rejected_steps += m.get('rejected_steps',0)
            min_dt, max_dt = min(min_dt, m['step_min_s']), max(max_dt, m['step_max_s'])
            minimum = min(minimum, m['minimum_aqueous_mol_m3'])
            max_charge = max(max_charge, m['max_charge_mol_m3'])
            max_charge_fraction = max(max_charge_fraction, m['max_normalized_charge'])
            max_current_residual = max(max_current_residual, m['max_current_residual_A_m2'])
            max_voltage_residual = max(max_voltage_residual, m['max_voltage_residual_V'])
            max_inv_error = np.maximum(max_inv_error, [m['max_relative_inventory_errors'][k] for k in ('Cu','Na','NO3')])
            for key in max_chem:
                max_chem[key] = max(max_chem[key], m['max_chemistry_residuals'][key])
            native_chemistry_stats['max_iterations'] = max(native_chemistry_stats['max_iterations'], m['max_chemistry_iterations'])
            native_chemistry_stats['algebraic_calls'] += m['algebraic_chemistry_calls']
            native_chemistry_stats['generic_calls'] += m['generic_chemistry_calls']
            native_chemistry_stats['max_local_charge_residual_mol_m3'] = max(native_chemistry_stats['max_local_charge_residual_mol_m3'], m['max_local_chemistry_charge_residual_mol_m3'])
            native_chemistry_stats['max_local_Cu_residual_mol_m3'] = max(native_chemistry_stats['max_local_Cu_residual_mol_m3'], m['max_local_chemistry_Cu_residual_mol_m3'])
            faradaic_moles += m['faradaic_moles_each_electrode_per_m2']
            signed_charge += m['integrated_signed_current_C_m2']
            chunk_current_min = m['current_stage_min_A_m2']
            chunk_current_max = m['current_stage_max_A_m2']
            t = target
            record()
            continue
        while t < target-1e-9:
            if p.time_order == 2:
                c,cs,cp,dt,m=coupled_step(c,cs,cp,dx,D,min(p.dt,target-t),p)
                minimum=min(minimum,m['minimum_aqueous_mol_m3'])
                rejected_steps+=m['rejected_steps']
                max_charge=max(max_charge,m['max_charge_mol_m3'])
                max_charge_fraction=max(max_charge_fraction,m['max_normalized_charge'])
                max_current_residual=max(max_current_residual,m['max_current_residual_A_m2'])
                max_voltage_residual=max(max_voltage_residual,m['max_voltage_residual_V'])
                for key in max_chem:
                    max_chem[key]=max(max_chem[key],m['max_chemistry_residuals'][key])
                max_inv_error=np.maximum(max_inv_error,np.abs(inventories(c,cs,cp,dx,p)/initial-1))
                faradaic_moles+=m['mean_absolute_current_A_m2']*dt/F
                signed_charge+=m['mean_signed_current_A_m2']*dt
                chunk_current_min=min(chunk_current_min,m['current_stage0_A_m2'],m['current_stage1_A_m2'])
                chunk_current_max=max(chunk_current_max,m['current_stage0_A_m2'],m['current_stage1_A_m2'])
                min_dt,max_dt=min(min_dt,dt),max(max_dt,dt)
                t+=dt
                steps+=1
                continue
            el = electrical(c, dx, D, p)
            c, dt, _ = transport_step(c, el, min(p.dt, target-t), dx, p)
            minimum = min(minimum, float(np.min(c)))
            c, cs, cp, _ = react(c, cs, cp, p)
            minimum = min(minimum, float(np.min(c)))
            q = np.sum(p.z[:, None]*c, axis=0)
            denom = np.sum(np.abs(p.z[:, None]*c), axis=0)
            max_charge = max(max_charge, float(np.max(np.abs(q))))
            max_charge_fraction = max(max_charge_fraction, float(np.max(np.abs(q)/denom)))
            max_current_residual = max(max_current_residual, el['current_residual'])
            max_voltage_residual = max(max_voltage_residual, el['voltage_residual'])
            max_inv_error = np.maximum(max_inv_error, np.abs(inventories(c, cs, cp, dx, p)/initial-1))
            chem = chemistry_residuals(c, cs, cp, p)
            for key in max_chem:
                max_chem[key] = max(max_chem[key], chem[key])
            faradaic_moles += abs(el['j'])*dt/F
            signed_charge += el['j']*dt
            chunk_current_min = min(chunk_current_min,el['j'])
            chunk_current_max = max(chunk_current_max,el['j'])
            min_dt, max_dt = min(min_dt, dt), max(max_dt, dt)
            t += dt
            steps += 1
        t = target
        record()
    diagnostics = dict(version=VERSION, backend=backend, parameters=asdict(p), accepted_steps=steps,
        physical_constants=dict(F_C_mol=F,R_J_mol_K=Rg,T_K=T),
        species=dict(names=list(p.names),charges=p.z.tolist(),D0_m2_s=p.D0.tolist()),
        source_sha256=source_hashes,
        environment=dict(python=platform.python_version(),numpy=np.__version__,matplotlib=matplotlib.__version__),
        diagnostics_scope='Native invariant/residual extrema include all evaluated trial states; current envelopes include accepted stages only.',
        rejected_steps=rejected_steps,
        step_min_s=min_dt, step_max_s=max_dt, minimum_aqueous_mol_m3=minimum,
        max_charge_mol_m3=max_charge, max_normalized_charge=max_charge_fraction,
        max_current_residual_A_m2=max_current_residual,
        max_voltage_residual_V=max_voltage_residual,
        max_relative_inventory_errors=dict(zip(('Cu','Na','NO3'), max_inv_error.tolist())),
        max_chemistry_residuals=max_chem, initial_inventories_mol_m2=initial.tolist(),
        final_inventories_mol_m2=inventories(c, cs, cp, dx, p).tolist(),
        final_copper_pools_mol_m2=(np.array([c[2].sum(), cs.sum(), cp.sum()])*p.theta*dx).tolist(),
        faradaic_moles_each_electrode_per_m2=faradaic_moles,
        integrated_signed_current_C_m2=signed_charge,
        recovered_Cu_mol_m2=0.,
        final_current_A_m2=currents[-1], elapsed_s=time.perf_counter()-tic)
    if backend == 'native':
        diagnostics['native_chemistry_stats'] = native_chemistry_stats
    return dict(x=x, snapshots=snaps, times_s=np.array(times), currents=np.array(currents),
                inventory_series=np.array(series),phase_inventory_series=np.array(phase_series),
                signed_charge_C_m2=np.array(charge_series),faradaic_moles_series=np.array(faradaic_series),
                accepted_stage_current_envelopes=np.array(current_envelopes),diagnostics=diagnostics)


def validate_parameters(p):
    """Reject unsupported or inadmissible runs before touching output files."""
    if not isinstance(p.N,(int,np.integer)) or isinstance(p.N,bool) or p.N < 2:
        raise ValueError('N must be an integer >=2.')
    positive=('L','theta','tau','Kw','Ksp','nedge','Cu_tot0','Na0','dt','tend','output_dt')
    for name in positive:
        if not np.isfinite(getattr(p,name)) or getattr(p,name) <= 0:
            raise ValueError(f'{name} must be finite and positive for this tutorial.')
    if p.theta > 1 or p.tau < 1 or not np.isfinite(p.cfl) or not 0 < p.cfl < 1:
        raise ValueError('Require theta<=1, tau>=1 and 0<cfl<1.')
    if p.spatial_order not in (1,2) or p.time_order not in (1,2):
        raise ValueError('Spatial and temporal orders must be1 or2.')
    if not all(np.isfinite(getattr(p,k)) for k in ('V','keo','pH0','pH50')):
        raise ValueError('Voltage, keo and pH parameters must be finite.')
    if np.shape(p.D0)!=(5,) or not np.isfinite(p.D0).all() or np.min(p.D0)<=0:
        raise ValueError('Five positive finite molecular diffusion coefficients are required.')
    if np.shape(p.z)!=(5,) or not np.array_equal(p.z,[1.,-1.,2.,1.,-1.]):
        raise ValueError('The chemistry requires H/OH/Cu/Na/NO3 charges +1,-1,+2,+1,-1.')
    if min(p.tend,p.output_dt)<1e-8:
        raise ValueError('Simulation duration and output interval must be >=1e-8 s.')


def snapshot_prefix(t):
    """Stable, non-colliding names; retain t0/t21600 for integer times."""
    value=float(t)
    return 't'+(str(int(value)) if value.is_integer() else repr(value))


def save(res, out):
    out = Path(out)
    out.mkdir(parents=True, exist_ok=True)
    (out/'diagnostics.json').write_text(json.dumps(res['diagnostics'], indent=2))
    arrays = dict(x=res['x'], times_s=res['times_s'], currents=res['currents'],
                  inventory_series=res['inventory_series'])
    for key in ('phase_inventory_series','signed_charge_C_m2','faradaic_moles_series','accepted_stage_current_envelopes'):
        if key in res:
            arrays[key]=res[key]
    for t, snap in res['snapshots'].items():
        for key, value in snap.items():
            arrays[f'{snapshot_prefix(t)}_{key}'] = value
    arrays['snapshot_times_s']=np.array(list(res['snapshots']))
    np.savez_compressed(out/'states.npz', **arrays)
    np.savetxt(out/'current.csv', np.c_[res['times_s'], res['currents']], delimiter=',',
               header='time_s,instantaneous_current_density_A_m2', comments='')
    if 'signed_charge_C_m2' in res:
        means=np.diff(res['signed_charge_C_m2'])/np.diff(res['times_s'])
        np.savetxt(out/'current_intervals.csv',np.c_[res['times_s'][:-1],res['times_s'][1:],means,
            res['accepted_stage_current_envelopes'][1:]],delimiter=',',comments='',
            header='start_s,end_s,interval_mean_current_A_m2,accepted_stage_min_A_m2,accepted_stage_max_A_m2')
        np.savetxt(out/'phase_inventories.csv',np.c_[res['times_s'],res['phase_inventory_series']],
            delimiter=',',comments='',header='time_s,aqueous_Cu_mol_m2,sorbed_Cu_mol_m2,precipitated_Cu_mol_m2')
    plot(res, out, bin_width_m=None, stem='Figure7_corrected',phase_inventory_panel=True)
    plot(res, out, bin_width_m=None, stem='Figure7_unbinned')


def plot(res, out, bin_width_m=None, stem='Figure7_corrected',phase_inventory_panel=False):
    fig, ax = plt.subplots(1, 3, figsize=(13.4, 3.9))
    x = res['x']*100
    colors = ['#777777', '#427aa1', '#b27920', '#a34545']
    for index, (t, sn) in enumerate(res['snapshots'].items()):
        color = colors[index % len(colors)]
        ax[0].plot(x, sn['pH'], lw=1.8, color=color, label=f'{t/3600:g} h')
    ax[0].set(xlabel='Distance from anode (cm)', ylabel='pH')
    ax[0].set_title('(a) pH evolution', loc='left', fontsize=11)
    first = res['snapshots'][0.]
    last_t = max(res['snapshots'])
    last = res['snapshots'][last_t]
    pools=np.array([first['Cu_s'],last['c'][2],last['Cu_s'],last['Cu_ppt']])
    xp=x
    if bin_width_m is not None:
        length=res['diagnostics']['parameters']['L']
        if not np.isfinite(bin_width_m) or bin_width_m<=0:
            raise ValueError('Plotting bin width must be finite and positive.')
        edges=np.unique(np.r_[np.arange(0.,length,bin_width_m),length])
        cell_edges=np.linspace(0.,length,len(x)+1)
        overlap=np.maximum(0.,np.minimum(edges[1:,None],cell_edges[None,1:])-
                           np.maximum(edges[:-1,None],cell_edges[None,:-1]))
        pools=pools@overlap.T/np.diff(edges)
        xp=(edges[:-1]+edges[1:])*50
        np.savetxt(Path(out)/'copper_2mm_spatial_means.csv',np.c_[xp/100,pools.T],
            delimiter=',',header='x_m,initial_sorbed,final_aqueous,final_sorbed,final_precipitated',comments='')
    if phase_inventory_panel:
        inv=res['phase_inventory_series']
        for k,color,label,style in zip(range(3),['#b27920','#438560','#a34545'],
                                      ['Aqueous','Sorbed','Precipitated'],['-','--','-.']):
            ax[1].plot(res['times_s']/3600,inv[:,k],color=color,ls=style,lw=1.8,label=label)
        ax[1].plot(res['times_s']/3600,inv.sum(axis=1),':',color='#555555',lw=1.5,label='Total Cu')
        ax[1].set(xlabel='Time (h)',ylabel='Cu inventory (mol m$^{-2}$)',ylim=(0,None))
        ax[1].set_title('(b) Copper phase inventories',loc='left',fontsize=11)
    else:
        ax[1].plot(xp, pools[0], '--', color='#888888', label='Sorbed, initial')
        ax[1].plot(xp, pools[1], color='#b27920', label='Aqueous')
        ax[1].plot(xp, pools[2], '--', color='#438560', label='Sorbed')
        ax[1].plot(xp, pools[3], '-.', color='#a34545', label='Precipitated')
        ax[1].set(xlabel='Distance from anode (cm)', ylabel='Cu (mol m$^{-3}$ water equivalent)')
        bin_label=f' ({bin_width_m*1000:g}-mm means)' if bin_width_m else ' (cell means)'
        ax[1].set_title(f'(b) Copper at {last_t/3600:g} h'+bin_label, loc='left', fontsize=10)
    ax[2].plot(res['times_s']/3600, res['currents'], color='#244d70', lw=1.8)
    ax[2].set(xlabel='Time (h)', ylabel='Current density (A m$^{-2}$)')
    ax[2].set_title('(c) Current at constant voltage', loc='left', fontsize=11)
    for a in ax[:2]:
        a.legend(frameon=False, fontsize=8)
    for a in ax:
        a.spines[['top', 'right']].set_visible(False)
        a.tick_params(labelsize=9)
    fig.tight_layout(w_pad=1.8)
    for suffix in ('png', 'pdf', 'svg'):
        fig.savefig(Path(out)/f'{stem}.{suffix}', dpi=400, bbox_inches='tight')
    plt.close(fig)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--cells', type=int, default=100)
    parser.add_argument('--max-step', type=float, default=15.)
    parser.add_argument('--cfl', type=float, default=.4)
    parser.add_argument('--hours', type=float, default=36.)
    parser.add_argument('--output-seconds', type=float, default=600.)
    parser.add_argument('--backend', choices=('python','native'), default='python')
    parser.add_argument('--spatial-order', type=int, choices=(1,2), default=1)
    parser.add_argument('--time-order', type=int, choices=(1,2), default=1)
    parser.add_argument('--out', default='results')
    args = parser.parse_args()
    p = P(N=args.cells, dt=args.max_step, cfl=args.cfl, tend=args.hours*3600,
          spatial_order=args.spatial_order,time_order=args.time_order,output_dt=args.output_seconds)
    result = run(p, backend=args.backend)
    save(result, args.out)
    print(json.dumps(result['diagnostics'], indent=2))
